### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sfuhrm**
* Couldn't get it to build with target JDK 1.6 - switching to JDK 8 will probably frustrate some old fashioned people still working with JDK 1.6 (release 2006!)
* Updated some dependencies

### CODE REVIEW

**Comment by manoelcampos** [comment]
Don't you think if there are people still using Java 6, they can stick with an older version of the library? This way, you can move on a provide an updated version targeting Java 8. 
According to the [2020's JRebel Developer Productivity Report](https://www.jrebel.com/resources/java-developer-productivity-report-2020), Java 7 or older is used by only 7% of respondents, while Java 8 is used by 58% of people and Java 11 by 22%. 
If you target Java 8, you are embracing 80% of Java developers.

**Comment by manoelcampos** [comment]
Don't you think if there are people still using Java 6, they can stick with an older version of the library? This way, you can move on a provide an updated version targeting Java 8. 
According to the [2020's JRebel Developer Productivity Report](https://www.jrebel.com/resources/java-developer-productivity-report-2020), Java 7 or older is used by only 7% of respondents, while Java 8 is used by 58% of people and Java 11 by 22%. 
If you target Java 8, you are embracing 80% of Java developers.

**Comment by sfuhrm** [comment]
@manoelcampos thanks for the numbers, I didn't know them! Here are comparable numbers

Sticking with [out-of-maintenance](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) runtime versions is not an option IMHO. There are no security updates in your JDK and when you are using this library your machine obviously has internet connectivity without security updates.

My opionion: Sticking with legacy JDKs (Java 6 is not anymore in the list above!) means you're giving up the opportunity of choice.
Java 8 at least has got commercial LTS support.

I may have a strong position here, but I know from my own experience that the other way around doesn't work at all.

**Comment by manoelcampos** [comment]
Sorry, I don't know if I clearly understood what is your direction here. If you keep supporting Java 6, developers using that version must stick with an out-of-maintenance JDK anyway, which is bad as you said.

If you upgrade to Java 8, developers can use an up-to-date JDK so security risks are reduced. Furthermore, you benefit more developers.

If some developers insist on Java 6, as they are using an out-of-date JDK already, they can keep using the older library versions.

**Comment by sfuhrm** [comment]
Let me repeat my original problem: I was not able do compile this software with an up-to-date JDK / Maven. The obsolete-JDK-problem is dictating which JDK and Maven you need to use for compilation. Maybe my original point is a bit clearer now?

```
mvn clean package
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project YahooFinanceAPI: Compilation failure: Compilation failure: 
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

(Java 13, Maven 3.6.0)

Besides that, the Travis CI build is only validating [Java 8](https://github.com/sstrickx/yahoofinance-api/blob/develop/.travis.yml). 

Out of curiosity, which JDK/Maven are you using? Are you able to build the project?

I was sure that there would be some discussion and I think it is important to get different views on that.

**Comment by manoelcampos** [comment]
I get it now. I haven't tried to build it and if I try, I'll face the same issue you have.
The point is that currently, you can't target Java 6 anymore building from a recent JDK.
My proposal is that you don't build a new version targeting Java 6. You just let the existing version and binary as they are already. Then you use JDK 8 to build a new release targeting only Java 8.

Developers using JDK 6 can keep using the older version of the library since they are already using an ancient version of the JDK.

**Pull request closed without merging**
