### PR TITLE
Refactor getResult into two methods

### PR DESCRIPTION
**Pull request by chadworth**

### CODE REVIEW

**Comment by chadworth** [comment]
@sstrickx are you okay that I'm upgrading to Java 8 as well in this PR? I could drop that part of it if you prefer. Java 7 was EOL in April 2015 and Java 8 has already been adopted by the majority of the Java community. Most of the other projects I use like Play Framework, Spark, etc. have dropped Java 7 support, so I figured upgrading to Java 8 here too would be safe.

**Comment by sstrickx** [comment]
@chadworth I agree with your reasoning, however the upgrade to Java 8 should only be included in release 4.0.0 (which will already contain significant refactoring anyway) such that all the 3.x.x versions keep working with Java 6.
I'll create a separate branch for the 4.0.0 release when I find some time so we can do the merge over there.

**Comment by benmccann** [comment]
@sstrickx ok, I've updated this PR so that it doesn't use Java 8. let me know when you create the new branch and I can send a PR to do the upgrade to Java 8 separately and make the code more concise

3.x.x actually doesn't support Java 6 despite the code being compiled for Java 6 because okhttp only works with Java 7. so maybe we should upgrade to Java 7 on the 3.x branch?

**Comment by chadworth** [comment]
@sstrickx ok, I've updated this PR so that it doesn't use Java 8. let me know when you create the new branch and I can send a PR to do the upgrade to Java 8 separately and make the code more concise

I added Java 7 to Travis. I couldn't add Java 6 because okhttp only works with Java 7.

**Comment by chadworth** [comment]
@sstrickx would you be able to take a look at this PR? thanks!

**Pull request closed without merging**
